main:main.c cpu.c finv.c fsqrt.c fmul.c float.c fpu_ftoi.c fpu_itof.c fpu_floor.c fadd_2clk.c
	gcc -Wall -O3 -o rin main.c cpu.c finv.c fsqrt.c fmul.c float.c fpu_ftoi.c fpu_itof.c fpu_floor.c fadd_2clk.c -lm
